add setup postgres

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -27,19 +27,19 @@ jobs:
         python_version:
           ["3.7", "3.8", "3.9", "3.10"]
 
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: password
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+#    services:
+#      postgres:
+#        image: postgres
+#        env:
+#          POSTGRES_USER: postgres
+#          POSTGRES_PASSWORD: password
+#        ports:
+#          - 5432:5432
+#        options: >-
+#          --health-cmd pg_isready
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
 
     steps:
       - uses: actions/checkout@v3
@@ -51,6 +51,28 @@ jobs:
           cache: "pip"
           cache-dependency-path: |
             **/requirements/*.txt
+      - uses: ankane/setup-postgres@v1
+        name: Install Postgres
+        with:
+          postgres-version: 14
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: password
+        run: |
+          echo "Check PostgreSQL service is running"
+          i=20
+          COMMAND='pg_isready'
+          while [ $i -gt 0 ]; do
+              echo "Check PostgreSQL service status"
+              eval $COMMAND && break
+              ((i--))
+              if [ $i == 0 ]; then
+                  echo "PostgreSQL service not ready, all attempts exhausted"
+                  exit 1
+              fi
+              echo "PostgreSQL service not ready, wait 3 more sec, attempts left: $i"
+              sleep 3
+          done
       - name: Install nox
         run: python3 -m pip install nox
       - name: Run nox
